Reformat files
- Only echo once
- Ran `shfmt -s -w -i 2 .`

diff --git a/blocks/systemctl-failed b/blocks/systemctl-failed
--- a/blocks/systemctl-failed
+++ b/blocks/systemctl-failed
@@ -1,15 +1,13 @@
 #!/bin/bash
 failed=$(systemctl --failed)
 regex="([0-9]+) loaded units listed.*"
-if [[ "$failed" =~ $regex ]]
-then
-    failed_count="${BASH_REMATCH[1]}"
-    if [[ "$failed_count" -gt 0 ]];
-    then
-        echo "$failed_count"
-        echo "$failed_count"
-        exit 33
-    fi
+if [[ $failed =~ $regex ]]; then
+  failed_count="${BASH_REMATCH[1]}"
+  if [[ $failed_count -gt 0 ]]; then
+    echo "$failed_count"
+    exit 33
+  fi
 else
-    echo "Failed to match"
+  echo "Failed to match"
+  exit 33
 fi
